version: '2'
services:
 sonarqube:
  image:
   sonarqube:8.9.7-community 
   ports: 
   - "9000:9000"
   volumes: 
   - 'SonarQube_data:/opt/SonarQube/data' 
   - 'SonarQube_extensions:/opt/SonarQube/extensions' 
   - 'SonarQube_logs:/opt/SonarQube/logs' 
  nexus:
   image: sonatype/nexus3 ports: - "8081:8081"
   volumes: 
   - 'nexus-data:/nexus-data' 
  volumes: 
   SonarQube_data: 
   SonarQube_extensions: 
   SonarQube_logs: 
   nexus-data:
   
   services:

  mysql-db:
    image: mysql:5.6
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'achatdb'
    ports:
      - target: 3306
        published: 3306
        protocol: tcp 
    volumes:
      - /home/mysql/data:/home/vagrant/mysql:rw
  
  springboot-app:
  
    image: alaaben/devops_project:latest
    container_name: springboot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      MYSQL_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: achatdb
    restart: on-failure
    ports:
      - 8084:8084 
    links:
      - mysql-db
   
  