version: "3.3"
services:   
   mysql-db:
    image: mysql:5.6
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'achatdb'
    ports:
      - target: 3306
        published: 3306
        protocol: tcp 
    volumes:
      - /home/mysql/data:/home/vagrant/mysql:rw
      
      
    